#!/usr/bin/env python3
"""Wrap the manual into a standalone page for GitHub Pages.

``docs/manual.html`` holds the manual's *content* - title, stylesheet link,
styles, then the page itself - with no ``<!doctype>``, ``<html>``, ``<head>`` or
``<body>`` around it.  That is deliberate: it is published as an Artifact, and
the Artifact service supplies that skeleton itself, so a file that carried its
own would end up with two.

GitHub Pages serves the file as it stands, and a document with no doctype is
rendered in quirks mode - a different box model, so table and padding widths
shift.  This script writes ``docs/index.html``, the same manual inside a proper
standalone document: a doctype, a declared character set so the degree signs and
angstroms survive, a viewport so it reads on a phone, and ``color-scheme`` so the
browser's own scrollbars follow the page into dark mode.

The name is the other half of it.  Pages serves ``index.html`` for a directory
and nothing else, so ``manual.html`` alone gives a 404 at the site root however
the repository is configured.

Run this whenever ``docs/manual.html`` changes, and commit the result::

    python scripts/build_pages.py

It is deliberately a build step rather than a second copy to edit: the manual has
one source, and ``docs/index.html`` says in its first line that it is generated.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "docs" / "manual.html"
TARGET = ROOT / "docs" / "index.html"

# The content starts with the head material - title, font stylesheet, styles -
# and the document proper begins at the navigation rail.
BODY_STARTS_AT = "<nav id="

SKELETON = """<!doctype html>
<!-- Generated by scripts/build_pages.py from docs/manual.html.  Do not edit:
     edit the manual and run the script again. -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<meta name="color-scheme" content="light dark">
<meta name="description" content="{description}">
{head}
</head>
<body>
{body}
</body>
</html>
"""

DESCRIPTION = (
    "ClayQuant user and reference manual: calculation of X-ray powder diffraction "
    "patterns of interstratified clay minerals, and quantification of clay mineral "
    "assemblages from oriented mounts."
)


def split(content: str) -> tuple[str, str]:
    """Separate the head material from the document body.

    Raises rather than guessing: a silently mis-split manual would publish with
    its stylesheet in the body, which renders as an unstyled wall of text and is
    the kind of failure nobody notices until someone else opens the page.
    """
    start = content.find(BODY_STARTS_AT)
    if start < 0:
        raise SystemExit(
            f"{SOURCE}: cannot find {BODY_STARTS_AT!r}, so the head and body "
            "cannot be told apart; check what the manual now begins with"
        )
    head, body = content[:start].strip(), content[start:].strip()
    if "<style>" not in head or "<title>" not in head:
        raise SystemExit(f"{SOURCE}: the part before {BODY_STARTS_AT!r} has no title or styles")
    return head, body


def build() -> str:
    content = SOURCE.read_text(encoding="utf-8")
    for tag in ("<!doctype", "<html", "<body"):
        if tag in content.lower():
            raise SystemExit(
                f"{SOURCE}: already contains {tag!r}.  This script adds the document "
                "skeleton, and the Artifact service adds one too, so the manual must "
                "not carry its own."
            )
    head, body = split(content)
    return SKELETON.format(description=DESCRIPTION, head=head, body=body)


def main(argv: list[str]) -> int:
    page = build()
    if "--check" in argv:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != page:
            print(f"{TARGET} is out of date; run python scripts/build_pages.py")
            return 1
        print(f"{TARGET} is up to date")
        return 0
    TARGET.write_text(page, encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT)} ({len(page):,} characters)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
